export const BINGO_WORDS: readonly string[] = [
  'hallucination',
  'emergent behavior',
  'AGI',
  'sentient',
  'alignment',
  'stochastic parrot',
  'Chinese Room',
  'Turing Test',
  'just predicts tokens',
  'it understands',
  "it can't truly think",
  'p(doom)',
  'singularity',
  'superintelligence',
  'black box',
  'fine-tuning',
  'RLHF',
  'jailbreak',
  'prompt engineering',
  'paradigm shift',
  'revolutionary',
  "we're cooked",
  'consciousness',
  'attention mechanism',
  'temperature',
  "it's just autocomplete",
  'AGI is here',
  'open source will win',
  'neural network',
  'gradient descent',
  'truly intelligent',
  'groundbreaking',
  "it thinks it's...",
  'next token prediction',
  'eliezer was right',
  'yann was right',
  'it can reason',
  'latent space',
  'world model',
  'in-context learning',
  'chain of thought',
  'multimodal',
  "it's alive",
  'tool use',
  'autonomous agent',
  'recursive self-improvement',
  'cognitive architecture',
  'retrieval-augmented',
  'it passed the test',
  'GPT-N will fix it',
];
