export const E = {
  PORT_IN_USE: 'DVPT-001',
  MODULE_NOT_FOUND: 'DVPT-002',
  BUILD_FAILED: 'DVPT-003',
  TS_ERROR: 'DVPT-004',
  INSTALL_FAILED: 'DVPT-005',
  RUNTIME_ERROR: 'DVPT-006',
  WEBSOCKET_ERROR: 'DVPT-007',
  CONNECTION_REFUSED: 'DVPT-008',
  TIMEOUT: 'DVPT-009',
  OUT_OF_MEMORY: 'DVPT-010',
  UNKNOWN: 'DVPT-999',
} as const;

export type ErrorCode = typeof E[keyof typeof E];
