import { redis, reddit } from '@devvit/web/server';
import type { OnModMailRequest } from '@devvit/web/shared';
import { logger, logZSet } from '../logger';
import type { PostId } from '../types';
import { type AppealRecord, appealKey } from '../action-modules/appeal';

const log = logger('appeal-moderator');
const APPEAL_LOG_KEY = 'bot:appeal:log';
const APPEAL_LOG_MAX = 200;

export async function run(event: OnModMailRequest): Promise<void> {
  if (event.conversationType !== 'sr_user') return;
  if (event.isAutoGenerated) return;

  const conversationId = event.conversationId;
  const senderName = event.messageAuthor?.name ?? '';
  if (!senderName) return;

  let subject: string;
  try {
    const { conversation } = await reddit.modMail.getConversation({ conversationId });
    subject = conversation?.subject ?? '';
  } catch (err) {
    log.warn('Could not fetch modmail conversation', { conversationId, error: (err as Error).message });
    return;
  }

  const match = subject.match(/^APPEAL:\s+(DELETE|REVIEW)\s+(t3_\w+)$/i);
  if (!match) return;

  const [, action, postId] = match;
  const key = appealKey(postId);

  const raw = await redis.get(key);
  if (!raw) {
    await reply(conversationId, 'No active appeal found for this post.');
    return;
  }

  const record: AppealRecord = JSON.parse(raw);

  if (record.state !== 'pending') {
    await reply(conversationId, 'This appeal has already been resolved.');
    return;
  }

  if (senderName !== record.authorName) {
    await reply(conversationId, 'Only the post author can use this appeal link.');
    return;
  }

  if (action.toUpperCase() === 'DELETE') {
    try {
      await reddit.remove(postId as PostId, false);
    } catch (err) {
      log.warn('Could not remove post', { postId, error: (err as Error).message });
      await reply(conversationId, 'Failed to remove the post. Please contact the mods directly.');
      return;
    }
    record.state = 'removed';
    await redis.set(key, JSON.stringify(record));
    await reply(conversationId, 'Your post has been removed.');
    await logZSet(APPEAL_LOG_KEY, { action: 'appeal_delete', postId, by: senderName }, APPEAL_LOG_MAX);
    log.info('Appeal: post removed', { postId, by: senderName });
  } else {
    try {
      await reddit.modMail.createModDiscussionConversation({
        subredditId: record.subredditId as `t5_${string}`,
        subject: `Fix review requested: "${record.postTitle}"`,
        bodyMarkdown: `u/${senderName} has fixed their post and requests a review.\n\n[View post](${record.postUrl})`,
      });
    } catch (err) {
      log.warn('Could not create mod discussion', { postId, error: (err as Error).message });
      await reply(conversationId, 'Failed to notify mods. Please contact them directly.');
      return;
    }
    record.state = 'review_requested';
    await redis.set(key, JSON.stringify(record));
    await reply(conversationId, 'Mods have been notified to review your changes. Thank you for following up!');
    await logZSet(APPEAL_LOG_KEY, { action: 'appeal_review', postId, by: senderName }, APPEAL_LOG_MAX);
    log.info('Appeal: review requested', { postId, by: senderName });
  }
}

async function reply(conversationId: string, body: string): Promise<void> {
  try {
    await reddit.modMail.reply({ conversationId, body });
  } catch (err) {
    log.warn('Could not reply to modmail', { conversationId, error: (err as Error).message });
  }
}
