theme: jekyll-theme-minimal
title: Reddit Devvit Apps - Legal Documentation
description: Terms of Service and Privacy Policies
url: "https://allhailseizure.github.io"
baseurl: "/Reddit-Devvit"
markdown: kramdown
